// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
export interface ILoginViewModuleCss {
  closeIcon: string;
  errorIcon: string;
  form: string;
  input: string;
  loginButton: string;
  snackbarContent: string;
  snackbarMessage: string;
  texts: string;
  title: string;
}

export const locals: ILoginViewModuleCss;
export default locals;
