// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
export interface IScreenViewModuleCss {
  base: string;
  withCenteredContent: string;
}

export const locals: IScreenViewModuleCss;
export default locals;
